#!/usr/bin/env python3

import enum
import os

import hid

SwitchPosition = enum.Enum("SwitchPosition", ["UP", "DOWN", "NEUTRAL"])


def get_L2_position():
    device = [
        device
        for device in hid.enumerate()
        if device["product_string"] in ("FrSky Simulator", "BetaFPV Taranis Joystick")
    ][0]

    gamepad = self.device()
    gamepad.open(device["vendor_id"], device["product_id"])
    gamepad.set_nonblocking(True)

    report = self.gamepad.read(64)
    event = [r - 256 if r > 127 else r for r in report]
    L2 = event[8]

    if L2 > 0:
        return SwitchPosition.UP
    elif L2 < 0:
        return SwitchPosition.DOWN
    else:
        return SwitchPosition.NEUTRAL


def main():
    if get_L2_position() == SwitchPosition.UP:
        os.execlp(
            "python3",
            "/home/pi/puppersim/puppersim/isaac_gym_policy.py",
            "--run_on_robot",
        )
    else:
        os.execlp("python3", "/home/pi/StanfordQuadruped/run_djipupper.py")


if __name__ == "__main__":
    main()
